pagerank_matrix: pagerank.hpp main.cpp pagerank_hot_cold.hpp main_hot_cold.cpp
	# baseline Og
	g++ -Og -Wall -std=c++17 -o pr_baseline_Og main.cpp 
	# separating hot and cold data Og
	g++ -Og -Wall -std=c++17 -o pr_hot_cold_Og main_hot_cold.cpp 
	# baseline O3
	g++ -O3 -Wall -std=c++17 -o pr_baseline_O3 main.cpp 
	# separating hot and cold data O3
	g++ -O3 -Wall -std=c++17 -o pr_hot_cold_O3 main_hot_cold.cpp 