pagerank_matrix: pagerank.hpp main.cpp pagerank_hot_cold.hpp main_hot_cold.cpp
	# baseline
	g++ -Og -Wall -std=c++17 -o pr_baseline main.cpp 
	# separating hot and cold data
	g++ -Og -Wall -std=c++17 -o pr_hot_cold main_hot_cold.cpp 
