all: pageRank.hpp main.cpp aos.cpp soa.cpp soa_v2.cpp
	# baseline
	g++ -Og -Wall -std=c++17 -o main main.cpp
	# aos
	g++ -Og -Wall -std=c++17 -o aos aos.cpp 
	# soa
	g++ -Og -Wall -std=c++17 -o soa soa.cpp 
	# soa different version
	g++ -Og -Wall -std=c++17 -o soa_v2 soa_v2.cpp 